# Generated by Django 4.0.1 on 2022-02-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='bio_dir',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='director',
            name='segundo_apellido_dir',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
