# Generated by Django 4.0.1 on 2022-02-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_director_bio_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='avatar',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Foto'),
        ),
    ]
