# Generated by Django 4.0.1 on 2022-02-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_director_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='avatar',
        ),
        migrations.AddField(
            model_name='director',
            name='avatar_dir',
            field=models.ImageField(null=True, upload_to='static/bootstrap4/fotos', verbose_name='Foto'),
        ),
    ]
