# Generated by Django 4.0.1 on 2022-02-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_director_avatar_director_avatar_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='avatar_dir',
            field=models.ImageField(null=True, upload_to='catalog/static/bootstrap4/fotos', verbose_name='Foto'),
        ),
    ]
