# Generated by Django 4.0.1 on 2022-02-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_director_avatar_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='avatar_dir',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
