# Generated by Django 4.0.1 on 2022-02-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_director_avatar_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='avatar_pel',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
