# Generated by Django 4.0.1 on 2022-02-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_peliculas_avatar_pel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frases_directores', models.CharField(max_length=100)),
            ],
        ),
    ]
