# Generated by Django 4.0.1 on 2022-02-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_frases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
