# Generated by Django 4.0.1 on 2022-02-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_peliculas_trailer_pel_alter_director_bio_dir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='estreno_pel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
